### ISSUE TITLE
Loading Custom Data sets

### ISSUE THREAD

**Issue by DavidAwad** [IBM-Bluemix/watson-QA-demo#1]
Just wanted to know if we can customize the data sets that we ask watson questions about? 

That would lead to much more interesting to use.

**Comment by gamedeff** [comment]
+1.

**Comment by JakePeyser** [comment]
Currently, the Q&A beta service only offers Healthcare and Travel data sets (known as a corpus) to query against. Ultimately, users will be able to submit and query against their own corpus, which will require its own training to be accurately queried by the Q&A service.
